# Generated by Django 5.0.2 on 2024-02-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vr_tanque', models.CharField(max_length=100)),
                ('fecha_ini', models.CharField(max_length=100)),
                ('fecha_fin', models.CharField(max_length=100)),
                ('vr_volumen', models.CharField(max_length=100)),
                ('vr_vol_ct', models.CharField(max_length=100)),
                ('vr_agua', models.CharField(max_length=100)),
                ('vr_temp', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
